/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SubmitQuestionRouteImport } from './routes/submit-question'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlayIndexRouteImport } from './routes/play.index'
import { Route as QuestionsIdRouteImport } from './routes/questions.$id'
import { Route as PlayThemeIdRouteImport } from './routes/play.$themeId'
import { Route as QuestionsIdEditRouteImport } from './routes/questions.$id_.edit'

const SubmitQuestionRoute = SubmitQuestionRouteImport.update({
  id: '/submit-question',
  path: '/submit-question',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayIndexRoute = PlayIndexRouteImport.update({
  id: '/play/',
  path: '/play/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestionsIdRoute = QuestionsIdRouteImport.update({
  id: '/questions/$id',
  path: '/questions/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayThemeIdRoute = PlayThemeIdRouteImport.update({
  id: '/play/$themeId',
  path: '/play/$themeId',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestionsIdEditRoute = QuestionsIdEditRouteImport.update({
  id: '/questions/$id_/edit',
  path: '/questions/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/submit-question': typeof SubmitQuestionRoute
  '/play/$themeId': typeof PlayThemeIdRoute
  '/questions/$id': typeof QuestionsIdRoute
  '/play': typeof PlayIndexRoute
  '/questions/$id/edit': typeof QuestionsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/submit-question': typeof SubmitQuestionRoute
  '/play/$themeId': typeof PlayThemeIdRoute
  '/questions/$id': typeof QuestionsIdRoute
  '/play': typeof PlayIndexRoute
  '/questions/$id/edit': typeof QuestionsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/submit-question': typeof SubmitQuestionRoute
  '/play/$themeId': typeof PlayThemeIdRoute
  '/questions/$id': typeof QuestionsIdRoute
  '/play/': typeof PlayIndexRoute
  '/questions/$id_/edit': typeof QuestionsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/submit-question'
    | '/play/$themeId'
    | '/questions/$id'
    | '/play'
    | '/questions/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/submit-question'
    | '/play/$themeId'
    | '/questions/$id'
    | '/play'
    | '/questions/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/submit-question'
    | '/play/$themeId'
    | '/questions/$id'
    | '/play/'
    | '/questions/$id_/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  SubmitQuestionRoute: typeof SubmitQuestionRoute
  PlayThemeIdRoute: typeof PlayThemeIdRoute
  QuestionsIdRoute: typeof QuestionsIdRoute
  PlayIndexRoute: typeof PlayIndexRoute
  QuestionsIdEditRoute: typeof QuestionsIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/submit-question': {
      id: '/submit-question'
      path: '/submit-question'
      fullPath: '/submit-question'
      preLoaderRoute: typeof SubmitQuestionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/': {
      id: '/play/'
      path: '/play'
      fullPath: '/play'
      preLoaderRoute: typeof PlayIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/questions/$id': {
      id: '/questions/$id'
      path: '/questions/$id'
      fullPath: '/questions/$id'
      preLoaderRoute: typeof QuestionsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/$themeId': {
      id: '/play/$themeId'
      path: '/play/$themeId'
      fullPath: '/play/$themeId'
      preLoaderRoute: typeof PlayThemeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/questions/$id_/edit': {
      id: '/questions/$id_/edit'
      path: '/questions/$id/edit'
      fullPath: '/questions/$id/edit'
      preLoaderRoute: typeof QuestionsIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  SubmitQuestionRoute: SubmitQuestionRoute,
  PlayThemeIdRoute: PlayThemeIdRoute,
  QuestionsIdRoute: QuestionsIdRoute,
  PlayIndexRoute: PlayIndexRoute,
  QuestionsIdEditRoute: QuestionsIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
